In [2]:
import pandas as pd

data = pd.read_csv("C:/Users/Marcel Palma/Directorio Principal/project_7/vehicles_us.csv")
data

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51520,9249,2013.0,nissan maxima,like new,6.0,gas,88136.0,automatic,sedan,black,NaN,2018-10-03,37
51521,2700,2002.0,honda civic,salvage,4.0,gas,181500.0,automatic,sedan,white,NaN,2018-11-14,22
51522,3950,2009.0,hyundai sonata,excellent,4.0,gas,128000.0,automatic,sedan,blue,NaN,2018-11-15,32
51523,7455,2013.0,toyota corolla,good,4.0,gas,139573.0,automatic,sedan,black,NaN,2018-07-02,71
51524,6300,2014.0,nissan altima,good,4.0,gas,NaN,automatic,sedan,NaN,NaN,2018-06-05,10

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  object
 3   condition     51525 non-null  object
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  object
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  object
 8   type          51525 non-null  object
 9   paint_color   42258 non-null  object
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  object
 12  days_listed   51525 non-null  int64
dtypes: float64(4), int64(2), object(7)
memory usage: 5.1+ MB

In [4]:
# Limpieza de nombres de columna
data.columns = data.columns.str.strip().str.lower().str.replace(" ", "_")
data

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51520,9249,2013.0,nissan maxima,like new,6.0,gas,88136.0,automatic,sedan,black,NaN,2018-10-03,37
51521,2700,2002.0,honda civic,salvage,4.0,gas,181500.0,automatic,sedan,white,NaN,2018-11-14,22
51522,3950,2009.0,hyundai sonata,excellent,4.0,gas,128000.0,automatic,sedan,blue,NaN,2018-11-15,32
51523,7455,2013.0,toyota corolla,good,4.0,gas,139573.0,automatic,sedan,black,NaN,2018-07-02,71
51524,6300,2014.0,nissan altima,good,4.0,gas,NaN,automatic,sedan,NaN,NaN,2018-06-05,10

In [5]:
import pandas as pd

# Suponiendo que tu DataFrame se llama 'data'

columnas_object = data.select_dtypes(include=['object']).columns

for col in columnas_object:
    try:
        data[col] = data[col].str.lower()
    except AttributeError:
        print(f"Error al convertir a minúsculas la columna '{col}'. Puede que contenga valores no convertibles a string.")

# Para verificar los cambios (opcional)
for col in columnas_object:
    print(f"Valores únicos en '{col}' después de convertir a minúsculas:")
    print(data[col].unique()[:20]) # Mostrar los primeros 20 valores únicos

print(data.head()) # Para ver las primeras filas del DataFrame con los cambios

Valores únicos en 'model' después de convertir a minúsculas:
['bmw x5' 'ford f-150' 'hyundai sonata' 'chrysler 200' 'chrysler 300'
 'toyota camry' 'honda pilot' 'kia sorento' 'chevrolet silverado 1500'
 'honda accord' 'ram 1500' 'gmc yukon' 'jeep cherokee'
 'chevrolet traverse' 'hyundai elantra' 'chevrolet tahoe' 'toyota rav4'
 'chevrolet silverado' 'jeep wrangler' 'chevrolet malibu']
Valores únicos en 'condition' después de convertir a minúsculas:
['good' 'like new' 'fair' 'excellent' 'salvage' 'new']
Valores únicos en 'fuel' después de convertir a minúsculas:
['gas' 'diesel' 'other' 'hybrid' 'electric']
Valores únicos en 'transmission' después de convertir a minúsculas:
['automatic' 'manual' 'other']
Valores únicos en 'type' después de convertir a minúsculas:
['suv' 'pickup' 'sedan' 'truck' 'coupe' 'van' 'convertible' 'hatchback'
 'wagon' 'mini-van' 'other' 'offroad' 'bus']
Valores únicos en 'paint_color' después de convertir a minúsculas:
[nan 'white' 'red' 'black' 'blue' 'grey' 'silver' 'custom' 'orange'
 'yellow' 'brown' 'green' 'purple']
Valores únicos en 'date_posted' después de convertir a minúsculas:
['2018-06-23' '2018-10-19' '2019-02-07' '2019-03-22' '2019-04-02'
 '2018-06-20' '2018-12-27' '2019-01-07' '2018-07-16' '2019-02-15'
 '2018-09-17' '2019-03-28' '2019-01-14' '2019-01-31' '2018-05-15'
 '2018-12-30' '2018-08-16' '2019-04-09' '2018-08-25' '2018-08-05']
   price  model_year           model  condition  cylinders fuel  odometer  \
0   9400      2011.0          bmw x5       good        6.0  gas  145000.0
1  25500         NaN      ford f-150       good        6.0  gas   88705.0
2   5500      2013.0  hyundai sonata   like new        4.0  gas  110000.0
3   1500      2003.0      ford f-150       fair        8.0  gas       NaN
4  14900      2017.0    chrysler 200  excellent        4.0  gas   80903.0

  transmission    type paint_color  is_4wd date_posted  days_listed
0    automatic     suv         NaN     1.0  2018-06-23           19
1    automatic  pickup       white     1.0  2018-10-19           50
2    automatic   sedan         red     NaN  2019-02-07           79
3    automatic  pickup         NaN     NaN  2019-03-22            9
4    automatic   sedan       black     NaN  2019-04-02           28

In [6]:
data

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,suv,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51520,9249,2013.0,nissan maxima,like new,6.0,gas,88136.0,automatic,sedan,black,NaN,2018-10-03,37
51521,2700,2002.0,honda civic,salvage,4.0,gas,181500.0,automatic,sedan,white,NaN,2018-11-14,22
51522,3950,2009.0,hyundai sonata,excellent,4.0,gas,128000.0,automatic,sedan,blue,NaN,2018-11-15,32
51523,7455,2013.0,toyota corolla,good,4.0,gas,139573.0,automatic,sedan,black,NaN,2018-07-02,71
51524,6300,2014.0,nissan altima,good,4.0,gas,NaN,automatic,sedan,NaN,NaN,2018-06-05,10

In [7]:
def tienen_decimales(serie):
    """Verifica si una Serie numérica (float) tiene valores con decimales distintos de cero."""
    return (serie % 1 != 0).any()

columnas_float = data.select_dtypes(include=['float64']).columns

print("Columnas de tipo float64 y si contienen decimales distintos de cero:")
for col in columnas_float:
    if col in data.columns:
        tiene = tienen_decimales(data[col].dropna()) # Excluir NaN para evitar errores
        print(f"- {col}: {tiene}")

Columnas de tipo float64 y si contienen decimales distintos de cero:
- model_year: False
- cylinders: False
- odometer: False
- is_4wd: False

In [8]:
import pandas as pd

# Convertir 'price' a float64
data['price'] = data['price'].astype('float64')

# Convertir 'model_year' a Int64 (entero nullable)
data['model_year'] = data['model_year'].astype('Int64')

# Convertir 'cylinders' a Int64 (entero nullable)
data['cylinders'] = data['cylinders'].astype('Int64')

# Convertir 'odometer' a Int64 (entero nullable)
data['odometer'] = data['odometer'].astype('Int64')

# Convertir 'is_4wd' a boolean (manejando NaN como False - reconsiderar si la falta de info no implica False)
data['is_4wd'] = data['is_4wd'].fillna(False)
data['is_4wd'] = data['is_4wd'].astype('bool')

# Convertir 'date_posted' a datetime64[ns]
data['date_posted'] = pd.to_datetime(data['date_posted'])

# 'days_listed' ya está en int64, no necesita conversión

# 'paint_color'está como 'object' pero se rellena con 'No Disponible' para la lógica backend
data['paint_color'] = data['paint_color'].fillna('No Disponible')

# Verificar
print(data.info())

# Filas
print(data.head(10))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  float64
 1   model_year    47906 non-null  Int64
 2   model         51525 non-null  object
 3   condition     51525 non-null  object
 4   cylinders     46265 non-null  Int64
 5   fuel          51525 non-null  object
 6   odometer      43633 non-null  Int64
 7   transmission  51525 non-null  object
 8   type          51525 non-null  object
 9   paint_color   51525 non-null  object
 10  is_4wd        51525 non-null  bool
 11  date_posted   51525 non-null  datetime64[ns]
 12  days_listed   51525 non-null  int64
dtypes: Int64(3), bool(1), datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 4.9+ MB
None
     price  model_year           model  condition  cylinders fuel  odometer  \
0   9400.0        2011          bmw x5       good          6  gas    145000
1  25500.0        <NA>      ford f-150       good          6  gas     88705
2   5500.0        2013  hyundai sonata   like new          4  gas    110000
3   1500.0        2003      ford f-150       fair          8  gas      <NA>
4  14900.0        2017    chrysler 200  excellent          4  gas     80903
5  14990.0        2014    chrysler 300  excellent          6  gas     57954
6  12990.0        2015    toyota camry  excellent          4  gas     79212
7  15990.0        2013     honda pilot  excellent          6  gas    109473
8  11500.0        2012     kia sorento  excellent          4  gas    104174
9   9200.0        2008     honda pilot  excellent       <NA>  gas    147191

  transmission    type    paint_color  is_4wd date_posted  days_listed
0    automatic     suv  No Disponible    True  2018-06-23           19
1    automatic  pickup          white    True  2018-10-19           50
2    automatic   sedan            red   False  2019-02-07           79
3    automatic  pickup  No Disponible   False  2019-03-22            9
4    automatic   sedan          black   False  2019-04-02           28
5    automatic   sedan          black    True  2018-06-20           15
6    automatic   sedan          white   False  2018-12-27           73
7    automatic     suv          black    True  2019-01-07           68
8    automatic     suv  No Disponible    True  2018-07-16           19
9    automatic     suv           blue    True  2019-02-15           17

In [9]:
import pandas as pd

data.rename(columns={
    'cylinders': 'num_cylinders',
    'is_4wd': 'has4wd'
}, inplace=True)

print(data.columns)

Index(['price', 'model_year', 'model', 'condition', 'num_cylinders', 'fuel',
       'odometer', 'transmission', 'type', 'paint_color', 'has4wd',
       'date_posted', 'days_listed'],
      dtype='object')

In [10]:
data

,price,model_year,model,condition,num_cylinders,fuel,odometer,transmission,type,paint_color,has4wd,date_posted,days_listed
0,9400.0,2011,bmw x5,good,6,gas,145000,automatic,suv,No Disponible,True,2018-06-23,19
1,25500.0,<NA>,ford f-150,good,6,gas,88705,automatic,pickup,white,True,2018-10-19,50
2,5500.0,2013,hyundai sonata,like new,4,gas,110000,automatic,sedan,red,False,2019-02-07,79
3,1500.0,2003,ford f-150,fair,8,gas,<NA>,automatic,pickup,No Disponible,False,2019-03-22,9
4,14900.0,2017,chrysler 200,excellent,4,gas,80903,automatic,sedan,black,False,2019-04-02,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51520,9249.0,2013,nissan maxima,like new,6,gas,88136,automatic,sedan,black,False,2018-10-03,37
51521,2700.0,2002,honda civic,salvage,4,gas,181500,automatic,sedan,white,False,2018-11-14,22
51522,3950.0,2009,hyundai sonata,excellent,4,gas,128000,automatic,sedan,blue,False,2018-11-15,32
51523,7455.0,2013,toyota corolla,good,4,gas,139573,automatic,sedan,black,False,2018-07-02,71
51524,6300.0,2014,nissan altima,good,4,gas,<NA>,automatic,sedan,No Disponible,False,2018-06-05,10

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          51525 non-null  float64
 1   model_year     47906 non-null  Int64
 2   model          51525 non-null  object
 3   condition      51525 non-null  object
 4   num_cylinders  46265 non-null  Int64
 5   fuel           51525 non-null  object
 6   odometer       43633 non-null  Int64
 7   transmission   51525 non-null  object
 8   type           51525 non-null  object
 9   paint_color    51525 non-null  object
 10  has4wd         51525 non-null  bool
 11  date_posted    51525 non-null  datetime64[ns]
 12  days_listed    51525 non-null  int64
dtypes: Int64(3), bool(1), datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 4.9+ MB

In [13]:
data.to_parquet('data_limpia.parquet', index=False)